### PR TITLE
Custom Link Component 

### LINKED ISSUE #1753: 🐛 Megamenu - Error Occurs on Click
As per my conversation with @ricksu978, when the "SSW Rules" link is clicked on in the megamenu, it throws an error. 

image
**Figure: output after clicking the link**

```[tasklist]
### Tasks
- [x] Fix issue for "SSW Rules"
- [x] Fix issue for "Our People"
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/1832
```

### LINKED ISSUE #1832: Add Custom Link component for all links
Implement a conditional rendering strategy using either next/link or <a> based on the URL type (external or internal). This approach aims to prevent client-side exceptions during data prefetching for external sites by choosing the appropriate link component dynamically.

```[tasklist]
### Tasks
- [x] Create a Custom Link Component
- [x] Replace all links with this component
- [ ] https://github.com/SSWConsulting/SSW.Website/issues/963
```

### PR DESCRIPTION
**Pull request by amankumarrr**
- Adding component to choose the appropriate link component dynamically.
- Adding 'Nofollow' tag reference 
 
- Affected routes:  `/*` 

- Fixed #1832 & #963

- [ ] Include done video or screenshots

### CODE REVIEW

File: components/customLink.tsx [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+      isExternalSSWSite() ||
+      (href.startsWith("https://") && !href.includes("ssw.com.au")) // checking relative path and external domains i.e. /company
+    );
+  };
+
+  const isExternalSSWSite = (): boolean => {
+    return externalSSWSitePatterns.some((pattern) =>
+      new RegExp(`^${pattern}`).test(href)
+    );
+  };
```
Comment (Harry-Ross) [inline components/customLink.tsx]: As per conversation, can you move these functions outside of the component to avoid needing to add the eslint-ignore?

File: components/customLink.tsx [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+
+  useEffect(() => {
+    setIsExternal(isExternalLink());
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [href]);
```
Comment (Harry-Ross) [inline components/customLink.tsx]: We may be able to do this without a useEffect and useState, just by using derived state from the props. 

https://react.dev/learn/you-might-not-need-an-effect

File: components/customLink.tsx [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+
+  return (
+    <>
+      {isExternal ? (
+        <a
+          className={className}
+          href={href}
+          target={target || "_blank"}
+          rel="noopener noreferrer nofollow"
```
Comment (Harry-Ross) [inline components/customLink.tsx]: We shouldn't have these rels for TV, Rules and People, as these are still internal links - probably check for if the link is on ssw.com.au for this one.

File: components/blocks/serviceCards.tsx [hunk 4]
```diff
@@ -137,19 +137,19 @@ const SmallCards = ({ title, cards, schema }) => {
...
+              </CustomLink>
             ) : (
-              <Link
+              <CustomLink
                 href={card.link ?? ""}
                 className="unstyled flex h-full flex-col"
               >
                 <SmallCardContent card={card} schema={schema} index={index} />
-              </Link>
+              </CustomLink>
```
Comment (Harry-Ross) [inline components/blocks/serviceCards.tsx]: Both results of this conditional are the same, you can probably remove `isExternal` from the Tina schema as well as removing this condition.

File: components/blocks/industryRenderer.tsx [hunk 5]
```diff
@@ -1,30 +1,30 @@
...
 import Button from "../button/button";
+import { CustomLink } from "../customLink";
 import { YouTubeEmbed } from "../embeds/youtubeEmbed";
 import { componentRenderer } from "./mdxComponentRenderer";
 import { SolutionsRow } from "./solutionsRow";
 
 export const DownloadWhitepaperLink = ({ whitepaperFile, children }) => (
-  <Link href={whitepaperFile} passHref legacyBehavior>
+  <CustomLink href={whitepaperFile}>
     <a target="_blank">{children}</a>
```
Comment (Harry-Ross) [inline components/blocks/industryRenderer.tsx]: Do we need this <a> tag on the inside anymore?

**Review by Harry-Ross — CHANGES_REQUESTED** [review]

File: components/customLink.tsx (hunk 1 above)
Comment (amankumarrr) [reply components/customLink.tsx]: Done - moved them outside

File: components/customLink.tsx (hunk 2 above)
Comment (amankumarrr) [reply components/customLink.tsx]: You're right, in our scenario we don't need to use Effect here. Removed it.

File: components/customLink.tsx (hunk 3 above)
Comment (amankumarrr) [reply components/customLink.tsx]: Done - Excluding all domains having `ssw` to have rel.

File: components/blocks/serviceCards.tsx (hunk 4 above)
Comment (amankumarrr) [reply components/blocks/serviceCards.tsx]: Removed.

File: components/blocks/industryRenderer.tsx (hunk 5 above)
Comment (amankumarrr) [reply components/blocks/industryRenderer.tsx]: Removed the inner anchor tag.

**Review by Harry-Ross — APPROVED** [review]
LGTM ✈️
