### PR TITLE
Fixing - Inconsistent testimonials and making them orderable 

### LINKED ISSUE #2056: 🐛 Inconsistent Testimonials
URL: https://www.ssw.com.au/training/internship-fullstack

**Describe the bug**
After each new deployment, testimonials on the training page vary, leading to confusion. We need to ensure consistency in testimonials to avoid this issue.

**To Reproduce**
1. Go to Tina Admin 
2. Open Training page
3. Toggle Hide/Show `Show Testimonials`

**Expected behavior**
It should consistently fetch the same testimonials with every retrieval.

**Screenshots/Video**
image

**Figure: Internship testimonials showing Brady in it instead of Jeoffrey**

### PR DESCRIPTION
**Pull request by amankumarrr**
Fixed: #2056

Also related 
- #2008 

**Existing Bug on Production:**
 
Testomonial-Tyla-Offices

**Figure: Showing testimonial from Tyla on `/offices/sydney`**

Affected routes: 
### Ordered Testimonials
- `/events/*`
**Number of testimonials**: first 3 on specificized category in `Tina`
**Test**: https://app-sswwebsite-9eb3-pr-2089.azurewebsites.net/events/clean-architecture-workshop

- `/training/*`
    **Categories** - `Internship`
    **Number of testimonials**: first 3
**Test**: https://app-sswwebsite-9eb3-pr-2089.azurewebsites.net/training/internship-fullstack
- `/company/testimonials`
**Categories excluding**: `Internship` and `Brainstorming` from `Tina` 
**Test**: https://app-sswwebsite-9eb3-pr-2089.azurewebsites.net/company/testimonials

### Random Testimonials
- `/offices`
**Categories excluding**: `Internship` and `Brainstorming`
**Number of testimonials**: 1
**Test**: https://app-sswwebsite-9eb3-pr-2089.azurewebsites.net/offices
- `/offices/*`
**Categories excluding**: `Internship` and `Brainstorming`
**Number of testimonials**: 1
**Test**: https://app-sswwebsite-9eb3-pr-2089.azurewebsites.net/offices/brisbane 
- `/netug/`
**Categories**: `User Group` and specified in `Tina`
**Test**: https://app-sswwebsite-9eb3-pr-2089.azurewebsites.net/netug/brisbane
- `/company/about-us`
**Test**: https://app-sswwebsite-9eb3-pr-2089.azurewebsites.net/company/about-us

- `/consulting/*`
**Number of testimonials**: 3
**Test**: https://app-sswwebsite-9eb3-pr-2089.azurewebsites.net/consulting/angular

✅ Consolidated testimonial files into a single file.
✅ Enabled testimonial ordering functionality.
✅ Successfully improved loading time for testimonials (`/company/testimonials`) from 5-6 seconds to under 1 second.

❌Testimonials can't have any embedded components

**Screenshot:**
Testomonial-Editable-Tina
**Figure: "Testimonials can be ordered in Tina now"**

### CODE REVIEW

File: components/offices/testimonialPanel.tsx [hunk 1]
```diff
@@ -1,21 +1,19 @@
...
-  };
+  body?: string;
+  name?: string;
+  company?: string;
 };
 
-const TestimonialPanel = ({ testimonial }: TestimonialPanelProps) => {
+const TestimonialPanel = ({ props }) => {
+  if (!props) return <></>;
+  const { body, name, company }: TestimonialPanelProps = JSON.parse(props);
```
Comment (wicksipedia) [inline components/offices/testimonialPanel.tsx]: JSON.parse shouldn't be necessary - bad code smell

File: content/consulting/brainstorming.mdx [hunk 2]
```diff
@@ -16,7 +16,7 @@ solution:
   project: Brainstorming
 callToAction: 'Talk to us about {{TITLE}}'
 testimonialCategories:
-  - testimonialCategory: content/testimonialCategories/brainstorming.mdx
+  - testimonialCategory: content/testimonialCategories/Brainstorming.mdx
```
Comment (wicksipedia) [inline content/consulting/brainstorming.mdx:19]: prefer kebab-case filenames as per rules

File: helpers/getTestimonials.ts [hunk 3]
```diff
@@ -1,40 +1,103 @@
...
+  name: string;
+  avatar?: string;
+  company?: string;
+  body?: string;
+};
+const SSWInternalTestimonialCategories = ["internship", "brainstorming"];
+
+export const getTestimonialsByCategories = async (
+  categories: string[] = [],
+  isOrdered: boolean = true
```
Comment (wicksipedia) [inline helpers/getTestimonials.ts]: i'd recommend not having this 2nd param as:
- it's name isn't that clear (have to look at the code to work out what it does)
- it breaks SRP

instead have a method like `getRandomTestimonialsByCategory` which calls this method under the hood, and then randomises the return value

File: helpers/getTestimonials.ts [hunk 4]
```diff
@@ -1,40 +1,103 @@
...
+    (testimonial) => ({
+      value: toStringify(testimonial),
+      label: `${testimonial.name} - ${testimonial.company ?? ""}`,
+    })
+  );
+
+  return testimonialOptions;
+};
+
+const toStringify = (testimonial: TestimonialType) =>
```
Comment (wicksipedia) [inline helpers/getTestimonials.ts]: the usage of this method seems very odd - why are we passing around json strings instead of the typescript objects?

File: components/blocks/testimonialsList.tsx [hunk 5]
```diff
@@ -1,45 +1,27 @@
...
-
   useEffect(() => {
-    const loadTestimonials = () => {
-      client.queries.testimonialsConnection().then((data) => {
-        const testimonials = data.data?.testimonialsConnection?.edges?.map(
-          (edge) => edge?.node
-        );
+    const loadTestimonials = async () => {
+      const filteredTestimonials = await getFilteredTestimonials(
+        listOfCategoriesToHide
```
Comment (wicksipedia) [inline components/blocks/testimonialsList.tsx]: given the method name - I would've expected that any param I would pass in would be to filter the return values to the ones I want to show, not hide - consider renaming the method name

File: pages/offices/[filename].tsx [hunk 6]
```diff
@@ -189,7 +190,7 @@ const SidePanel = ({ office, testimonial }) => {
     <div className="prose max-w-full">
       <ContactPanel office={office} />
       <MicrosoftPanel />
-      <TestimonialPanel testimonial={testimonial} />
+      <TestimonialPanel props={testimonial} />
```
Comment (wicksipedia) [inline pages/offices/[filename].tsx]:
```suggestion
      <TestimonialPanel {...testimonial} />
```

File: content/company/about-us.mdx [hunk 7]
```diff
@@ -4,17 +4,12 @@ seo:
...
 sidebar: |
   <MicrosoftPanel />
-sidebarTestimonial: content/testimonials/System77.mdx
+sidebarTestimonial: >-
```
Comment (wicksipedia) [inline content/company/about-us.mdx]: change the schema to be an object instead of a string

File: pages/offices/index.tsx [hunk 8]
```diff
@@ -119,7 +120,7 @@ export default function OfficeIndex(
                 </ul>
                 <div className="hidden sm:block">
                   <MicrosoftPanel />
-                  <TestimonialPanel testimonial={props.testimonial} />
+                  <TestimonialPanel props={props.testimonial} />
```
Comment (wicksipedia) [inline pages/offices/index.tsx]:
```suggestion
                  <TestimonialPanel{...props.testimonial} />
```

File: helpers/getTestimonials.ts (hunk 3 above)
Comment (amankumarrr) [reply helpers/getTestimonials.ts]: I agree - Fixed

File: components/blocks/testimonialsList.tsx (hunk 5 above)
Comment (amankumarrr) [reply components/blocks/testimonialsList.tsx]: done - changed the method name to `getTestimonialsExcludingCategories`

Comment (amankumarrr) [reply components/blocks/testimonialsList.tsx]: and variable name to `excludedCategories`

File: content/consulting/brainstorming.mdx (hunk 2 above)
Comment (amankumarrr) [reply content/consulting/brainstorming.mdx:19]: Considering 'Brainstorming' is a single word and all categories are in uppercase, for consistency, should we modify the casing of all testimonials categories to lower-case? and their respective testimonials?

Comment (wicksipedia) [reply content/consulting/brainstorming.mdx:19]: yes, kebab case implies lower case
i'd log it as tech debt and fix it later though as it will muddy this pr

File: components/offices/testimonialPanel.tsx (hunk 1 above)
Comment (amankumarrr) [reply components/offices/testimonialPanel.tsx]: Fixed - Now passing a name as a string to retrieve the testimonial.

File: pages/offices/[filename].tsx (hunk 6 above)
Comment (amankumarrr) [reply pages/offices/[filename].tsx]: Not done - I'm passing name as a string to this component

File: content/company/about-us.mdx (hunk 7 above)
Comment (amankumarrr) [reply content/company/about-us.mdx]: Not done - as discussed yesterday, to handle this as a dropdown field, I'm passing a name of the testimonial as a value of dropdown field.

File: pages/offices/index.tsx (hunk 8 above)
Comment (amankumarrr) [reply pages/offices/index.tsx]: Not done - as per reason mentioned above.

File: helpers/getTestimonials.ts (hunk 4 above)
Comment (amankumarrr) [reply helpers/getTestimonials.ts]: done - removed this function and now passing this as an object

File: content/consulting/brainstorming.mdx (hunk 2 above)
Comment (amankumarrr) [reply content/consulting/brainstorming.mdx:19]: Done - here is the issue - https://github.com/SSWConsulting/SSW.Website/issues/2098

File: helpers/getTestimonials.ts [hunk 9]
```diff
@@ -1,40 +1,134 @@
...
+  if (!name) return null;
+
+  const testimonialResult = testimonialList.testimonials
+    .filter(
+      (testimonial) =>
+        testimonial.name && testimonial.name.toLowerCase() === name
+    )
+    .map((testimonial) => testimonial as TestimonialType)[0];
+
+  return testimonialResult ? toTestimonialPanelObject(testimonialResult) : null;
```
Comment (wicksipedia) [inline helpers/getTestimonials.ts]: If there are no testimonials found - I'd expect the indexer to cause the code to error out.

Comment (amankumarrr) [reply helpers/getTestimonials.ts]: Done

**Review by wicksipedia — APPROVED** [review]
we went through this together
