### PR TITLE
🐛 Bug - Added Custom Hook for Safe Use of Recaptcha key

### LINKED ISSUE #1285: 🐛 Bug - Potential Use of null Recaptcha Key
There is a potential edgecase where the value obtained from the React context for use w/ Recaptcha is null.

```[tasklist]
### Tasks
- [x] Create a custom useContext hook to throw an error when the recaptcha key is not provided through context
```

### PR DESCRIPTION
**Pull request by Harry-Ross**
* Added custom hook instead of using `useContext` in the Recaptcha component to ensure developers don't accidentially forget to use the context provider as a parent

- Affected routes: All routes w/ booking form

- Fixed #1285

- [ ] If adding a new page, I have followed the [SEO checklist](https://www.ssw.com.au/rules/seo-checklist/)

- [ ] Include done video or screenshots

### CODE REVIEW

File: context/RecaptchaContext.ts [hunk 1]
```diff
@@ -1,7 +1,15 @@
-import { createContext } from "react";
+import { createContext, useContext } from "react";
 
 export interface RecaptchaContextType {
-  recaptchaKey?: string;
+  recaptchaKey: string;
 }
 
 export const RecaptchaContext = createContext<RecaptchaContextType>(null);
```
Comment (amankumarrr) [inline context/RecaptchaContext.ts:7]: Do we need to export this anymore?

**Review by amankumarrr — APPROVED** [review]

**Review by amankumarrr — APPROVED** [review]

**Comment by Harry-Ross** [comment]
As per my conversation with @bradystroud, I will be continuing this PR when I am back in the office on Wednesday (31/8)

**Review by amankumarrr — APPROVED** [review]
Looks good!
