### PR TITLE
🐛 Hydration - Fix on Homepage

### LINKED ISSUE #2386: ⚠️ Megamenu - hydration errors are causing lighthouse scores to tank
When I was investigating #2385 and tried to run a lighthouse check locally for `/consulting/sharepoint` - hydration errors cause the score to tank

Image

Image

```[tasklist]
### Tasks
- [x] Fix hydration errors with megamenu
- [x] Investigate other hydration errors still occurring on production
```

### PR DESCRIPTION
**Pull request by Harry-Ross**
- Affected routes: `/`

- Fixed #2386

- [ ] If adding a new page, I have followed the [📃 New Webpage](https://github.com/SSWConsulting/SSW.Website/issues/new?assignees=&labels=&projects=&template=new_webpage.yml&title=%F0%9F%93%84+%7B%7B+TITLE+%7D%7D+) issue template

- [ ] Include done video or screenshots

### CODE REVIEW

File: components/blocks/aboutUs.tsx [hunk 1]
```diff
@@ -290,31 +297,39 @@ const OfficeInfo = ({ office }) => {
...
+
+const OpenStatus = ({ state }: OpenStatusProps) => {
+  const [status, setStatus] = useState<Status>("");
+  const timeZone = states[state]?.timeZone;
+
+  useEffect(() => {
+    const now = dayjs.utc().tz(timeZone);
+
+    const isWeekend = [DAY_KEYS.Saturday, DAY_KEYS.Sunday].some(
+      (x) => x === now.day()
```
Comment (amankumarrr) [inline components/blocks/aboutUs.tsx]: can we simplify this for more readability? (i.e [DAY_KEYS.Saturday, DAY_KEYS.Sunday].includes(now.day()))

File: components/blocks/aboutUs.tsx [hunk 2]
```diff
@@ -290,31 +297,39 @@ const OfficeInfo = ({ office }) => {
...
+    );
+    const currentHour = now.hour();
+
+    if (
+      isWeekend ||
+      currentHour < WORKING_TIME.Open ||
+      WORKING_TIME.Close < currentHour
```
Comment (amankumarrr) [inline components/blocks/aboutUs.tsx]: this should be in between the working hours so I think we should use && operator instead

**Review by amankumarrr — CHANGES_REQUESTED** [review]

**Review by amankumarrr — APPROVED** [review]
LGTM, pending on a new deployment
