### PR TITLE
🐛 Footer - DayJS RelativeTime Error

### LINKED ISSUE #899: 🐛 Consulting index error
**Describe the bug**
When you load the consulting index page, there is an error.

**To Reproduce**
1. Go to `/consulting`

image

### PR DESCRIPTION
**Pull request by Harry-Ross**
* Added global DayJS plugin additions to ensure bug cannot occur again

From my investigation, the reason why the `/consulting` route had a bug with `.fromNow()` function from the `dayjs/plugin/relativeTime` module, but not the other pages was because the `UpcomingEvents` component was imported by using the `<Blocks>` component, which contains `dayjs.extend(relativeTime)`. This wasn't noticed as most of the pages have the `<Blocks>` component in the page, which therefore loaded `UpcomingEvents` and the DayJS module extension. I have fixed this by having a single source of truth in the root app file for which DayJS modules have been loaded, which should make it clear to both devs and the TypeScript compiler which modules are available for use in the project.

I found the desired configuration at https://github.com/iamkun/dayjs/issues/1577. This means that by using `dayjs.extend()`, each subsequent use of DayJS will have the plugin used with the function.

Fixes #899

Affected routes:

- All (`<Footer />`)

### CODE REVIEW

File: components/blocks/upcomingEvents.tsx [hunk 1]
```diff
@@ -1,7 +1,5 @@
 import dayjs from "dayjs";
-import isBetween from "dayjs/plugin/isBetween";
-import relativeTime from "dayjs/plugin/relativeTime";
-import utc from "dayjs/plugin/utc";
+// import relativeTime from "dayjs/plugin/relativeTime";
```
Comment (bradystroud) [inline components/blocks/upcomingEvents.tsx]:
```suggestion
```

**Review by bradystroud — APPROVED** [review]
Thanks @Harry-Ross 

> From my investigation, the reason why the /consulting route had a bug with .fromNow() function from the dayjs/plugin/relativeTime module, but not the other pages was because the UpcomingEvents component was imported by using the <Blocks> component, which contains dayjs.extend(relativeTime). This wasn't noticed as most of the pages have the <Blocks> component in the page, which therefore loaded UpcomingEvents and the DayJS module extension. I have fixed this by having a single source of truth in the root app file for which DayJS modules have been loaded, which should make it clear to both devs and the TypeScript compiler which modules are available for use in the project.
> 
> I found the desired configuration at https://github.com/iamkun/dayjs/issues/1577. This means that by using dayjs.extend(), each subsequent use of DayJS will have the plugin used with the function.

When you close the issue, can you copy this info into it?
