### PR TITLE
🐛 Fix bug | missing validation and defaultValue for rating field

### LINKED ISSUE #1316: 🐛 Missing validation and defaultValue for rating field
**Describe the bug**
1. When we create new testimonials without configurating their ratings, there is no validation check on editing page.
2. Since rating field is required for component testimonial, fetching testimonials will throw exceptions(unseen on production), which makes even if you selected one category of the testimonials, it cannot fetch those testimonials properly.

**To Reproduce**
1. Add testimonials without configurating rating
2. Click save button
3. Add testimonial categories in one of the event pages
4. Only testimonials in category "General" show

**Expected behavior**
1. Validation on rating field and add defaultValue for the field
2. After configurating categories, show representative testimonials

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.
Remember to mark the area in the application thats impacted.

### PR DESCRIPTION
**Pull request by johnxu16**
- Affected routes: /admin

- Fixed #1316 

- [ ] If adding a new page, I have followed the [SEO checklist](https://www.ssw.com.au/rules/seo-checklist/)

- [x] Include done video or screenshots

image
**Figure: Add a testimonial without "rating"**

image
 **Figure: Add the testimonial created before on event page**

image
**Figure: TinaAdmin page throw a exception caused by empty field "rating"**

---
#### After change

image
**Figure: Add default value for the field "rating"**

### CODE REVIEW

File: components/testimonials/TestimonialRow.tsx [hunk 1]
```diff
@@ -33,7 +34,12 @@ export const TestimonialRow = ({
         What do people <span className="text-sswRed">say</span>?
       </h2>
       <p className="mb-8 text-center">{tagline}</p>
-      <div className="grid justify-center gap-6 md:grid-cols-autoFit3">
+      <div
+        className={cs(
+          "grid justify-center gap-6",
+          `md:grid-cols-${testimonialResult?.length ?? 3}`
```
Comment (amankumarrr) [inline components/testimonials/TestimonialRow.tsx]: Can you test it if it works with different value?

Comment (johnxu16) [reply components/testimonials/TestimonialRow.tsx]: Done

**Review by bradystroud — APPROVED** [review]
LGTM John

@amankumarrr can you please review again?
